### ISSUE TITLE
People deserve the truth

### ISSUE THREAD

**Issue by iCrawl** [RealBlazeIt/patron.js#1]
Maybe you should list some of the *actual* good frameworks, and not lie to people that yours is the "only" real flexible one, because that's just a big lie. You base this off of frameworks that are either in a heavy development stage (discord.js-commando) or haven't even looked at the ones listed below 👍 

- https://github.com/1Computer1/discord-akairo
- https://github.com/zajrik/yamdbf
- https://github.com/dirigeants/klasa
- https://github.com/Gawdl3y/discord.js-commando

**Comment by RealBlazeIt** [comment]
At the time I wrote the readme, there were no other frameworks I knew of that could accomplish what I felt a command framework needed. Many that I tried did things on my bot's behalf such as sending error messages in a fixed format, with no other way to handle the errors. That bothered me, so I made my own. I haven't heard of some of the frameworks you listed, so I will check them out. As for "people deserve the truth", I wouldn't think a boastful readme would bother so many people, so I guess I will tone it down a bit.
