### ISSUE TITLE
No spacing preservation with remainder arguments.

### ISSUE THREAD

**Issue by ghost** [RealBlazeIt/patron.js#9]
All remainder arguments are joined with a single space, however, they are originally split by *any* whitespace. This means that if tabs or several spaces were used in a remainder argument, the parsed value would simply replace all contiguous whitespace with a single space.

**Comment by LJNeon** [comment]
I would argue that this is beneficial and makes parsing/usage of remainder arguments easier. Unless there's a use case where you would need the exact whitespace that I'm missing?

**Comment by LJNeon** [comment]
Also looked into implementing this a little, and I believe it would require another regex, something like `/\s+(?=([^"]*"[^"]*")*[^"]*$)/g`, to select all whitespace not wrapped in double quotes. This would change based on the argument regex used which means adding another option would likely be required, as well as making sure that both are set if one is.

**Comment by ghost** [comment]
@LJNeon eval commands, kills all indentation unless its wrapped with quotes. Its just not something that should happen, but I cannot think of an elegant solution that would work even for custom parsing regexes.

**Comment by LJNeon** [comment]
That’s why I suggested adding another option for it, and eval itself ignores whitespace so the only problem would be displaying the input code in an eval command. Sounds more like preference than need. I’ll see if I can PR this next time I can get on a computer if it still needs to be done.

**Comment by ghost** [comment]
fixed
